# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9.1

language: swift

sudo: required

before_install:
- brew update
- brew outdated carthage || brew upgrade carthage

script:
- carthage update


